/* EduConnect — mobile-first school management prototype
   Storage: localStorage. Demo OTP: 123456.
   Roles: Student, Teacher, Admin.
*/
(function(){
'use strict';
const KEY='educonnect_v5';
const today=()=>new Date().toISOString().slice(0,10);
const uid=p=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const readFileMeta=files=>[...files].map(f=>({name:f.name,type:f.type||'file',size:f.size}));
const seed={
 school:{code:'DEMO01',name:'EduConnect Demo School',classes:['10','11','12'],sections:['A','B'],subjects:['Physics','Chemistry','Mathematics','English','Computer Science']},
 accounts:[],
 current:null,
 settings:{theme:'system',notifications:true,language:'English'},
 students:[{id:'s1',name:'Student One',phone:'9000000001',class:'11',section:'A',roll:'01',teachers:['t1','t2','t3']}],
 teachers:[{id:'t1',name:'Aarav Sharma',phone:'9000000011',subjects:['Physics'],classes:['11'],sections:['A']},{id:'t2',name:'Neha Verma',phone:'9000000012',subjects:['Chemistry'],classes:['11'],sections:['A']},{id:'t3',name:'Rohit Patil',phone:'9000000013',subjects:['Mathematics'],classes:['11'],sections:['A']}],
 attendance:[], homework:[{id:'hw1',title:'Kinematics Practice',subject:'Physics',class:'11',section:'A',due:today(),description:'Complete the assigned numerical problems.',files:[],createdBy:'t1',submissions:{}}],
 results:[{id:'r1',title:'Unit Test 1',class:'11',section:'A',subject:'Physics',date:today(),marks:10,max:20,studentMarks:{s1:16},published:true}],
 notices:[{id:'n1',title:'Welcome to EduConnect',body:'Check your dashboard for school updates.',class:'11',section:'A',files:[],date:today(),readBy:[],createdBy:'admin'}],
 notifications:[{id:'nt1',title:'Welcome',body:'Welcome to EduConnect.',type:'notice',date:today(),target:'11-A'}],
 ptm:[], leaves:[], events:[], feedback:[], exams:[{id:'ex1',title:'Unit Test 1',subject:'Physics',class:'11',section:'A',date:today(),time:'10:00'}]
};
let S=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x?merge(seed,x):structuredClone(seed)}catch(e){return structuredClone(seed)}}
function merge(a,b){const o=structuredClone(a);Object.keys(b||{}).forEach(k=>{if(b[k]!==undefined)o[k]=b[k]});return o}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function me(){if(!S.current)return null;return S[S.current.role+'s']?.find(x=>x.id===S.current.id)||S.current}
function role(){return S.current?.role||null}
function targetClass(){const m=me();return m&&m.class?`${m.class}-${m.section}`:''}
function notify(title,body,type,target){S.notifications.unshift({id:uid('nt'),title,body,type,date:today(),target:target||''});if(S.notifications.length>100)S.notifications.length=100}
function toast(msg){let t=document.getElementById('ec-toast');if(!t){t=document.createElement('div');t.id='ec-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function inject(){const st=document.createElement('style');st.textContent=`
.ec-card{position:relative;overflow:hidden;min-height:145px;cursor:pointer;transition:.18s}.ec-card:hover{transform:translateY(-2px)}.ec-ill{position:absolute;right:12px;bottom:4px;font-size:64px;opacity:.12;pointer-events:none}.ec-actions{display:flex;gap:8px;flex-wrap:wrap}.ec-empty{padding:25px;text-align:center;color:#7b8497}.ec-modal{position:fixed;inset:0;background:#10182866;z-index:30;display:grid;place-items:center;padding:16px}.ec-modalbox{width:min(760px,100%);max-height:90vh;overflow:auto;background:var(--ec-bg,#fff);color:var(--ec-fg,#172033);border-radius:20px;padding:20px;box-shadow:0 25px 80px #0003}.ec-close{float:right;border:0;background:transparent;font-size:25px}.ec-kpi{font-size:25px;font-weight:800}.ec-list{display:grid;gap:10px}.ec-item{padding:14px;border:1px solid #e5e9f2;border-radius:14px}.dark .ec-item,body.dark .ec-item{border-color:#374151;background:#1f2937}.dark{--ec-bg:#111827;--ec-fg:#e5e7eb}.ec-form{display:grid;gap:10px}.ec-form label{font-size:13px;font-weight:700}.ec-form input,.ec-form select,.ec-form textarea{width:100%;padding:11px;border:1px solid #e5e9f2;border-radius:11px;background:transparent;color:inherit}.dark .ec-form input,.dark .ec-form select,.dark .ec-form textarea,body.dark .ec-form input,body.dark .ec-form select,body.dark .ec-form textarea{border-color:#374151}.ec-tablewrap{overflow:auto}.ec-table{width:100%;border-collapse:collapse}.ec-table th,.ec-table td{padding:9px;border-bottom:1px solid #e5e9f2;text-align:left;white-space:nowrap}.ec-tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.ec-tabs button{border:1px solid #e5e9f2;background:transparent;padding:8px 11px;border-radius:10px}.ec-tabs button.on{background:#3157d5;color:white}.ec-topactions{display:flex;gap:7px;align-items:center}.ec-muted{color:#778196;font-size:13px}.ec-danger{background:#fee2e2!important;color:#b42318!important}.ec-success{background:#dcfce7!important;color:#166534!important}.ec-rolegrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ec-mini{font-size:12px}.ec-navbrand{cursor:pointer}.ec-notifdot{display:inline-block;width:8px;height:8px;background:#ef4444;border-radius:50%;margin-left:4px}.ec-file{font-size:12px;margin-top:5px}.ec-hero{background:linear-gradient(135deg,#edf1ff,#f7f9ff);border-radius:20px;padding:20px}.dark .ec-hero,body.dark .ec-hero{background:linear-gradient(135deg,#172554,#111827)}@media(max-width:600px){.ec-rolegrid{grid-template-columns:1fr}.ec-card{min-height:125px}.ec-ill{font-size:54px}.ec-modalbox{padding:16px}}
`;document.head.appendChild(st)}
function shell(){return `<div class="shell"><aside class="side" id="side"><div class="brand ec-navbrand" onclick="EC.go('home')"><img src="./icon-192.png"><span>EduConnect</span></div><div class="nav"><button onclick="EC.go('profile')">👤 Profile</button><button onclick="EC.go('settings')">⚙️ Settings</button><button onclick="EC.go('accounts')">🔄 Multiple Accounts</button><button onclick="EC.logout()">🚪 Logout</button></div></aside><main class="main"><div class="top"><div><button class="mobile" onclick="EC.side()">☰</button><h1 id="title">Dashboard</h1><div class="muted" id="sub">School management</div></div><div class="pill"><div class="avatar" id="avatar">E</div><span id="who">User</span></div></div><div id="view"></div></main></div>`}
function login(){document.body.innerHTML=`<div class="login"><div class="loginbox"><img src="./icon-192.png"><h1>EduConnect</h1><p class="muted">School management • Demo prototype</p><div class="form"><label>Role</label><div class="ec-rolegrid"><button class="role sel" data-role="Student">🎓 Student</button><button class="role" data-role="Teacher">👨‍🏫 Teacher</button><button class="role" data-role="Admin">🛡️ Admin</button></div><label>School Code</label><input class="input" id="lcode" value="DEMO01"><label>Phone</label><input class="input" id="lphone" placeholder="Enter phone number"><label>OTP</label><input class="input" id="lotp" placeholder="Demo OTP: 123456" inputmode="numeric"><button class="btn" id="sendotp">Send Demo OTP</button><button class="btn alt" id="loginbtn">Login</button><p id="lmsg" class="muted"></p></div></div></div>`;let rr='Student';document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{rr=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')});document.getElementById('sendotp').onclick=()=>{document.getElementById('lmsg').textContent='Demo OTP sent: 123456';document.getElementById('lotp').value='123456'};document.getElementById('loginbtn').onclick=()=>doLogin(rr)}
function doLogin(rr){const code=document.getElementById('lcode').value.trim().toUpperCase(),phone=document.getElementById('lphone').value.trim(),otp=document.getElementById('lotp').value.trim();if(code!==S.school.code)return alert('Use school code DEMO01 in this prototype.');if(otp!=='123456')return alert('Demo OTP is 123456.');let list=rr==='Student'?S.students:rr==='Teacher'?S.teachers:[];let u=list.find(x=>x.phone===phone);if(rr==='Admin'){u={id:'admin1',name:'School Admin',phone:phone||'9000000099'};}else if(!u){u={id:uid(rr[0].toLowerCase()),name:rr+' User',phone, ...(rr==='Student'?{class:'11',section:'A',roll:'99',teachers:['t1','t2','t3']}:{subjects:['General'],classes:['11'],sections:['A']})};list.push(u)}S.current={role:rr,id:u.id,name:u.name,phone:u.phone};const acc=S.accounts.find(a=>a.role===rr&&a.phone===u.phone);if(!acc)S.accounts.push({role:rr,id:u.id,name:u.name,phone:u.phone});save();render()}
function render(){if(!S.current){login();return}document.body.innerHTML=shell();inject();applyTheme();document.getElementById('who').textContent=me()?.name||S.current.name;document.getElementById('avatar').textContent=(me()?.name||'U')[0].toUpperCase();go('home')}
function side(){document.getElementById('side')?.classList.toggle('open')}
function setTitle(t,s=''){document.getElementById('title').textContent=t;document.getElementById('sub').textContent=s}
function go(page){document.getElementById('side')?.classList.remove('open');if(page==='home')dashboard();else if(page==='profile')profile();else if(page==='settings')settings();else if(page==='accounts')accounts();else if(page==='homework')homeworks();else if(page==='attendance')attendance();else if(page==='results')results();else if(page==='notices')notices();else if(page==='notifications')notifications();else if(page==='contacts')contacts();else if(page==='study')study();else if(page==='ptm')ptm();else if(page==='exam')exam();else if(page==='fees')fees();else if(page==='leave')leave();else if(page==='events')events();else if(page==='feedback')feedback();else if(page==='school')schoolManage()}
function put(html){document.getElementById('view').innerHTML=html}
function card(icon,title,desc,fn){return `<div class="card ec-card" onclick="EC.go('${fn}')"><div class="badge">${icon}</div><h3>${esc(title)}</h3><div class="muted">${esc(desc)}</div><div class="ec-ill">${icon}</div></div>`}
function dashboard(){setTitle('Dashboard',`${S.school.name} • ${role()}`);const r=role();let cards=[card('📚','Homework','Open assignments and submissions','homework'),card('🗓️','Attendance','View attendance details','attendance'),card('📊','Results','Tests, marks and percentages','results'),card('📢','Notices','School and class notices','notices'),card('🔔','Notifications','Updates from school','notifications'),card('👩‍🏫','Teacher Contacts','Teachers for this student/class','contacts'),card('🤖','Study AI','Text, image, PDF and voice tools','study'),card('📝','Exam Schedule','Upcoming exams','exam'),card('💳','Fees','Fee status and records','fees'),card('🧾','Leave','Apply and track leave','leave'),card('🎉','School Events','Events and activities','events'),card('💬','Feedback','Send feedback','feedback')];if(r!=='Student'){cards=cards.concat([card('🤝','PTM','Parent-teacher meeting records','ptm'),card('🏫','School Management','Classes, sections, subjects and people','school')])}put(`<div class="ec-hero"><div class="badge">${r}</div><h2>Welcome, ${esc(me()?.name||S.current.name)} 👋</h2><p class="muted">Tap a card to open its full section.</p></div><div class="head"><h2>Quick Access</h2></div><div class="grid2">${cards.join('')}</div>`)}
function profile(){setTitle('Profile','Your account information');const m=me();put(`<div class="card"><div class="avatar">${(m?.name||'U')[0]}</div><h2>${esc(m?.name)}</h2><p class="muted">Role: ${role()}</p><div class="ec-list"><div class="ec-item"><b>Phone</b><br>${esc(m?.phone||'')}</div>${m?.class?`<div class="ec-item"><b>Class / Section</b><br>${esc(m.class)} - ${esc(m.section)}</div>`:''}${m?.roll?`<div class="ec-item"><b>Roll No.</b><br>${esc(m.roll)}</div>`:''}<div class="ec-item"><b>School</b><br>${esc(S.school.name)} (${esc(S.school.code)})</div></div></div>`)}
function settings(){setTitle('Settings','Appearance, notifications and account');put(`<div class="grid2"><div class="card"><h3>Appearance</h3><div class="ec-tabs"><button class="${S.settings.theme==='light'?'on':''}" onclick="EC.theme('light')">☀️ White</button><button class="${S.settings.theme==='dark'?'on':''}" onclick="EC.theme('dark')">🌙 Dark</button><button class="${S.settings.theme==='system'?'on':''}" onclick="EC.theme('system')">📱 System Default</button></div><h3>Notifications</h3><button class="btn ${S.settings.notifications?'':'alt'}" onclick="EC.notifToggle()">${S.settings.notifications?'ON':'OFF'}</button></div><div class="card"><h3>Language</h3><select class="input" onchange="EC.language(this.value)"><option ${S.settings.language==='English'?'selected':''}>English</option><option ${S.settings.language==='Hindi'?'selected':''}>Hindi</option></select><h3>Account</h3><div class="ec-actions"><button class="btn alt" onclick="EC.go('accounts')">Another Account</button><button class="btn ghost" onclick="EC.logout()">Logout</button></div><h3>About</h3><p class="muted">EduConnect prototype v5. Local demo data is stored on this device/browser.</p></div></div>`)}
function accounts(){setTitle('Multiple Accounts','Switch accounts in one tap');const arr=S.accounts;put(`<div class="card"><div class="ec-actions"><button class="btn" onclick="EC.logout(true)">＋ Add Account</button></div><div class="ec-list" style="margin-top:15px">${arr.length?arr.map((a,i)=>`<div class="ec-item"><b>${esc(a.name)}</b><div class="ec-muted">${a.role} • ${esc(a.phone||'')}</div><button class="btn alt" style="margin-top:8px" onclick="EC.switchAcc(${i})">Switch</button></div>`).join(''):'<div class="ec-empty">No saved accounts.</div>'}</div></div>`)}
function logout(add){S.current=null;save();login()}
function switchAcc(i){const a=S.accounts[i];if(!a)return;S.current={role:a.role,id:a.id,name:a.name,phone:a.phone};save();render()}
function modal(title,body){const x=document.createElement('div');x.className='ec-modal';x.innerHTML=`<div class="ec-modalbox"><button class="ec-close" onclick="this.closest('.ec-modal').remove()">×</button><h2>${esc(title)}</h2>${body}</div>`;document.body.appendChild(x);return x}
function homeworks(){setTitle('Homework','Assignments and submissions');const r=role(),m=me();let list=S.homework.filter(h=>r!=='Student'||(h.class===m.class&&h.section===m.section));put(`<div class="head"><h2>Homework</h2>${r!=='Student'?'<button class="btn" onclick="EC.addHW()">＋ Add Homework</button>':''}</div><div class="ec-list">${list.map(h=>{const sub=h.submissions?.[m?.id];return `<div class="card"><div class="badge">${esc(h.subject)}</div><h3>${esc(h.title)}</h3><p>${esc(h.description)}</p><div class="ec-muted">Class ${esc(h.class)}-${esc(h.section)} • Due ${esc(h.due)}</div>${h.files?.length?`<div class="ec-file">📎 ${h.files.map(f=>esc(f.name)).join(', ')}</div>`:''}${r==='Student'?`<div class="ec-actions" style="margin-top:10px"><span class="badge ${sub?'ok':''}">${sub?'Submitted':'Not submitted'}</span>${!sub?`<button class="btn alt" onclick="EC.submitHW('${h.id}')">Mark as submitted</button>`:''}</div>`:`<div class="ec-actions" style="margin-top:10px"><button class="btn alt" onclick="EC.editHW('${h.id}')">Edit</button><button class="btn ghost" onclick="EC.delHW('${h.id}')">Delete</button></div>`}</div>`}).join('')||'<div class="ec-empty">No homework found.</div>'}</div>`)}
function hwForm(h){return `<div class="ec-form"><label>Title</label><input id="f_title" value="${esc(h?.title||'')}"><label>Subject</label><input id="f_subject" value="${esc(h?.subject||'')}" placeholder="Physics"><label>Class</label><input id="f_class" value="${esc(h?.class||'11')}"><label>Section</label><input id="f_section" value="${esc(h?.section||'A')}"><label>Due date</label><input id="f_due" type="date" value="${esc(h?.due||today())}"><label>Description</label><textarea id="f_desc">${esc(h?.description||'')}</textarea><label>Files (metadata stored in demo)</label><input id="f_files" type="file" multiple accept="image/*,.pdf"><button class="btn" onclick="EC.saveHW(${h?`'${h.id}'`:'null'})">Save Homework</button></div>`}
function addHW(){modal('Add Homework',hwForm())}function editHW(id){const h=S.homework.find(x=>x.id===id);modal('Edit Homework',hwForm(h))}
function saveHW(id){const f=id?S.homework.find(x=>x.id===id):{id:uid('hw'),submissions:{},createdBy:me()?.id};const old=f.files||[];f.title=document.getElementById('f_title').value.trim();f.subject=document.getElementById('f_subject').value.trim();f.class=document.getElementById('f_class').value.trim();f.section=document.getElementById('f_section').value.trim();f.due=document.getElementById('f_due').value;f.description=document.getElementById('f_desc').value.trim();const files=document.getElementById('f_files').files;f.files=old.concat(readFileMeta(files));if(!id)S.homework.unshift(f);notify('New homework',f.title,'homework',`${f.class}-${f.section}`);save();document.querySelector('.ec-modal')?.remove();homeworks();toast('Homework saved')}
function delHW(id){if(!confirm('Delete this homework?'))return;S.homework=S.homework.filter(x=>x.id!==id);save();homeworks()}function submitHW(id){const h=S.homework.find(x=>x.id===id),m=me();h.submissions=h.submissions||{};h.submissions[m.id]={date:today()};notify('Homework submitted',h.title,'homework',targetClass());save();homeworks();toast('Marked submitted')}
function attendance(){setTitle('Attendance','Date-wise attendance and PTM');const r=role(),m=me();if(r==='Student'){const rows=S.attendance.filter(a=>a.studentId===m.id).sort((a,b)=>b.date.localeCompare(a.date));const p=rows.filter(x=>x.status==='present').length,total=rows.length;put(`<div class="grid2"><div class="card"><div class="ec-kpi">${total?Math.round(p/total*100):0}%</div><div class="muted">Overall attendance</div></div><div class="card"><div class="ec-kpi">${p}/${total}</div><div class="muted">Present days</div></div></div><div class="head"><h2>Date-wise</h2></div><div class="ec-list">${rows.map(x=>`<div class="ec-item"><b>${x.date}</b><span class="badge ${x.status==='present'?'ok':''}">${x.status}</span></div>`).join('')||'<div class="ec-empty">No attendance records yet.</div>'}</div><div class="head"><h2>PTM Attendance</h2></div><div class="ec-list">${S.ptm.filter(x=>x.studentId===m.id).map(x=>`<div class="ec-item">${x.date} • ${x.status}</div>`).join('')||'<div class="ec-empty">No PTM records.</div>'}</div>`);return}put(`<div class="card"><div class="ec-form"><label>Date</label><input id="attdate" type="date" value="${today()}"><label>Class</label><input id="attclass" value="11"><label>Section</label><input id="attsection" value="A"><button class="btn" onclick="EC.loadAtt()">Load Students</button></div></div><div id="attlist" style="margin-top:12px"></div>`)}
function loadAtt(){const date=document.getElementById('attdate').value,cl=document.getElementById('attclass').value,sec=document.getElementById('attsection').value;const students=S.students.filter(s=>s.class===cl&&s.section===sec);let map={};S.attendance.filter(a=>a.date===date).forEach(a=>map[a.studentId]=a.status);document.getElementById('attlist').innerHTML=`<div class="card"><div class="ec-actions"><button class="btn alt" onclick="EC.markAllAtt('present')">Mark all present</button><button class="btn ghost" onclick="EC.markAllAtt('absent')">Mark all absent</button></div><div class="ec-list" id="attrows" style="margin-top:10px">${students.map(s=>`<div class="row"><div><strong>${esc(s.name)}</strong><span class="ec-muted">Roll ${esc(s.roll)}</span></div><select class="attselect" data-id="${s.id}"><option value="present" ${(map[s.id]||'present')==='present'?'selected':''}>Present</option><option value="absent" ${map[s.id]==='absent'?'selected':''}>Absent</option></select></div>`).join('')||'<div class="ec-empty">No students in this class.</div>'}</div><button class="btn" style="margin-top:12px" onclick="EC.saveAtt()">Save Attendance</button></div>`}
function markAllAtt(v){document.querySelectorAll('.attselect').forEach(x=>x.value=v)}function saveAtt(){const date=document.getElementById('attdate').value;document.querySelectorAll('.attselect').forEach(x=>{S.attendance=S.attendance.filter(a=>!(a.date===date&&a.studentId===x.dataset.id));S.attendance.push({id:uid('att'),date,studentId:x.dataset.id,status:x.value,markedBy:me()?.id})});notify('Attendance updated','Attendance was updated for '+date,'attendance');save();toast('Attendance saved')}
function results(){setTitle('Results','Published marks and class averages');const r=role(),m=me();if(r==='Student'){const rows=S.results.filter(x=>x.published&&x.class===m.class&&x.section===m.section);put(`<div class="ec-list">${rows.map(x=>{const mark=x.studentMarks?.[m.id];const pct=mark==null?null:mark/x.max*100;return `<div class="card"><div class="badge">${esc(x.subject)}</div><h3>${esc(x.title)}</h3><div class="ec-kpi">${mark==null?'—':mark+' / '+x.max}</div><div class="muted">${pct==null?'No marks':pct.toFixed(1)+'%'} • ${grade(pct)}</div><div class="ec-muted">${x.date}</div></div>`}).join('')||'<div class="ec-empty">No published results.</div>'}</div>`);return}const avg=classAverages();put(`<div class="card"><h3>Class / Section Averages</h3>${avg.length?`<div class="ec-tablewrap"><table class="ec-table"><tr><th>Class</th><th>Section</th><th>Average %</th></tr>${avg.map(a=>`<tr><td>${a.class}</td><td>${a.section}</td><td>${a.avg.toFixed(1)}%</td></tr>`).join('')}</table></div>`:'<div class="ec-empty">No marks to average.</div>'}</div><div class="head"><h2>Results</h2><button class="btn" onclick="EC.addResult()">＋ Add Result</button></div><div class="ec-list">${S.results.map(x=>`<div class="card"><div class="badge">${esc(x.subject)} • ${x.published?'Published':'Draft'}</div><h3>${esc(x.title)}</h3><p>Class ${esc(x.class)}-${esc(x.section)} • Max ${x.max} • ${x.date}</p><div class="ec-actions"><button class="btn alt" onclick="EC.editResult('${x.id}')">Edit</button><button class="btn ghost" onclick="EC.toggleResult('${x.id}')">${x.published?'Unpublish':'Publish'}</button><button class="btn ghost" onclick="EC.delResult('${x.id}')">Delete</button></div></div>`).join('')}</div>`)}
function grade(p){if(p==null)return '—';return p>=90?'A+':p>=80?'A':p>=70?'B':p>=60?'C':p>=50?'D':'E'}
function classAverages(){const out=[];for(const c of S.school.classes)for(const sec of S.school.sections){const rs=S.results.filter(x=>x.published&&x.class===c&&x.section===sec);let vals=[];rs.forEach(x=>Object.values(x.studentMarks||{}).forEach(v=>vals.push(v/x.max*100)));if(vals.length)out.push({class:c,section:sec,avg:vals.reduce((a,b)=>a+b,0)/vals.length})}return out}
function resultForm(x){const students=S.students.filter(s=>s.class===(x?.class||'11')&&s.section===(x?.section||'A'));return `<div class="ec-form"><label>Title</label><input id="r_title" value="${esc(x?.title||'Unit Test')}"><label>Subject</label><input id="r_subject" value="${esc(x?.subject||'Physics')}"><label>Class</label><input id="r_class" value="${esc(x?.class||'11')}"><label>Section</label><input id="r_section" value="${esc(x?.section||'A')}"><label>Date</label><input id="r_date" type="date" value="${esc(x?.date||today())}"><label>Maximum Marks</label><input id="r_max" type="number" value="${x?.max||20}"><label>Marks JSON (studentId:marks)</label><textarea id="r_marks">${esc(JSON.stringify(x?.studentMarks||Object.fromEntries(students.map(s=>[s.id,0])),null,2))}</textarea><button class="btn" onclick="EC.saveResult(${x?`'${x.id}'`:'null'})">Save Result</button></div>`}
function addResult(){modal('Add Result',resultForm())}function editResult(id){modal('Edit Result',resultForm(S.results.find(x=>x.id===id)))}function saveResult(id){let marks={};try{marks=JSON.parse(document.getElementById('r_marks').value||'{}')}catch(e){return alert('Marks JSON is invalid.')}const x=id?S.results.find(z=>z.id===id):{id:uid('r'),published:false};x.title=document.getElementById('r_title').value;x.subject=document.getElementById('r_subject').value;x.class=document.getElementById('r_class').value;x.section=document.getElementById('r_section').value;x.date=document.getElementById('r_date').value;x.max=Number(document.getElementById('r_max').value);x.studentMarks=marks;if(!id)S.results.unshift(x);notify('Result updated',x.title,'result',`${x.class}-${x.section}`);save();document.querySelector('.ec-modal')?.remove();results()}
function toggleResult(id){const x=S.results.find(z=>z.id===id);x.published=!x.published;if(x.published)notify('Result published',x.title,'result',`${x.class}-${x.section}`);save();results()}function delResult(id){if(confirm('Delete result?')){S.results=S.results.filter(x=>x.id!==id);save();results()}}
function notices(){setTitle('Notices','School and class announcements');const r=role(),m=me(),list=S.notices.filter(n=>r!=='Student'||(n.class===m.class&&n.section===m.section));put(`<div class="head"><h2>Notices</h2>${r!=='Student'?'<button class="btn" onclick="EC.addNotice()">＋ Add Notice</button>':''}</div><div class="ec-list">${list.map(n=>`<div class="card"><div class="badge">${n.readBy?.includes(m?.id)?'Read':'New'}</div><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><div class="ec-muted">${n.date} • ${esc(n.class)}-${esc(n.section)}</div>${n.files?.length?`<div class="ec-file">📎 ${n.files.map(f=>esc(f.name)).join(', ')}</div>`:''}<div class="ec-actions" style="margin-top:8px">${r==='Student'&&!n.readBy?.includes(m.id)?`<button class="btn alt" onclick="EC.readNotice('${n.id}')">Mark as read</button>`:''}${r!=='Student'?`<button class="btn alt" onclick="EC.editNotice('${n.id}')">Edit</button><button class="btn ghost" onclick="EC.delNotice('${n.id}')">Delete</button>`:''}</div></div>`).join('')||'<div class="ec-empty">No notices.</div>'}</div>`)}
function noticeForm(n){return `<div class="ec-form"><label>Title</label><input id="n_title" value="${esc(n?.title||'')}"/><label>Class</label><input id="n_class" value="${esc(n?.class||'11')}"/><label>Section</label><input id="n_section" value="${esc(n?.section||'A')}"/><label>Body</label><textarea id="n_body">${esc(n?.body||'')}</textarea><label>Attachment</label><input id="n_files" type="file" multiple accept="image/*,.pdf"><button class="btn" onclick="EC.saveNotice(${n?`'${n.id}'`:'null'})">Save Notice</button></div>`}
function addNotice(){modal('Add Notice',noticeForm())}function editNotice(id){modal('Edit Notice',noticeForm(S.notices.find(x=>x.id===id)))}function saveNotice(id){const n=id?S.notices.find(x=>x.id===id):{id:uid('n'),readBy:[],createdBy:me()?.id};n.title=document.getElementById('n_title').value;n.class=document.getElementById('n_class').value;n.section=document.getElementById('n_section').value;n.body=document.getElementById('n_body').value;n.date=today();n.files=(n.files||[]).concat(readFileMeta(document.getElementById('n_files').files));if(!id)S.notices.unshift(n);notify('New notice',n.title,'notice',`${n.class}-${n.section}`);save();document.querySelector('.ec-modal')?.remove();notices()}function readNotice(id){const n=S.notices.find(x=>x.id===id);n.readBy=n.readBy||[];if(!n.readBy.includes(me().id))n.readBy.push(me().id);save();notices()}function delNotice(id){if(confirm('Delete notice?')){S.notices=S.notices.filter(x=>x.id!==id);save();notices()}}
function notifications(){setTitle('Notifications','Homework, notices, results and attendance updates');const m=me(),tar=targetClass(),list=S.notifications.filter(n=>!n.target||n.target===tar||role()!=='Student');put(`<div class="ec-list">${list.map(n=>`<div class="card"><div class="badge">${esc(n.type)}</div><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><div class="ec-muted">${n.date}</div></div>`).join('')||'<div class="ec-empty">No notifications.</div>'}</div>`)}
function contacts(){setTitle('Teacher Contacts','Teachers connected to this student/class');const m=me();let ts=role()==='Student'?S.teachers.filter(t=>t.classes?.includes(m.class)&&t.sections?.includes(m.section)):S.teachers;put(`<div class="ec-list">${ts.map(t=>`<div class="card"><div class="badge">👩‍🏫 Teacher</div><h3>${esc(t.name)}</h3><p>${esc((t.subjects||[]).join(', '))}</p><p>📞 ${esc(t.phone)}</p></div>`).join('')||'<div class="ec-empty">No teacher contacts found.</div>'}</div>`)}
function study(){setTitle('Study AI','Prototype study assistant');put(`<div class="grid2"><div class="card"><h3>Ask a question</h3><textarea id="aiq" class="textarea" placeholder="Type your question..."></textarea><div class="ec-actions" style="margin-top:8px"><button class="btn" onclick="EC.askAI()">Explain</button><button class="btn alt" onclick="EC.voiceIn()">🎙️ Voice input</button></div><div id="aiout" style="margin-top:12px"></div></div><div class="card"><h3>Image / PDF</h3><input id="aifile" type="file" accept="image/*,.pdf"><p class="ec-muted">Files are handled as a prototype input only; no external AI API is connected.</p><button class="btn alt" onclick="EC.fileAI()">Read file name</button><h3>Voice reply</h3><button class="btn" onclick="EC.speakLast()">🔊 Speak last answer</button></div></div><div class="head"><h2>Chat History</h2><button class="btn ghost" onclick="EC.clearAI()">Clear</button></div><div id="aichat" class="ec-list">${(S.ai||[]).map(x=>`<div class="ec-item"><b>You:</b> ${esc(x.q)}<br><b>EduConnect:</b> ${esc(x.a)}</div>`).join('')||'<div class="ec-empty">No chats yet.</div>'}</div>`)}
function askAI(){const q=document.getElementById('aiq').value.trim();if(!q)return;const a='Demo Study AI: I can structure the question, explain the concept and show a step-by-step solution once a real school AI service is connected. For now, this prototype does not send your data to an AI API.';S.ai=S.ai||[];S.ai.push({q,a,date:today()});save();document.getElementById('aiout').innerHTML=`<div class="ec-item">${esc(a)}</div>`;document.getElementById('aichat').innerHTML=S.ai.map(x=>`<div class="ec-item"><b>You:</b> ${esc(x.q)}<br><b>EduConnect:</b> ${esc(x.a)}</div>`).join('');window.EC._last=a}
function voiceIn(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('Voice input is not supported in this browser.');const r=new R();r.lang='en-IN';r.onresult=e=>{document.getElementById('aiq').value=e.results[0][0].transcript};r.start()}
function speakLast(){const t=window.EC._last||S.ai?.at(-1)?.a;if(!t)return toast('Ask something first.');if(!speechSynthesis)return toast('Voice reply is not supported.');speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}function fileAI(){const f=document.getElementById('aifile').files[0];toast(f?`Selected: ${f.name}`:'Select an image or PDF first.')}function clearAI(){S.ai=[];save();study()}
function ptm(){setTitle('PTM','Parent-teacher meeting records');const r=role(),m=me();if(r==='Student'){const rows=S.ptm.filter(x=>x.studentId===m.id);put(`<div class="ec-list">${rows.map(x=>`<div class="card"><b>${x.date}</b><p>${esc(x.status)}</p><div class="muted">${esc(x.note||'')}</div></div>`).join('')||'<div class="ec-empty">No PTM records.</div>'}</div>`);return}put(`<div class="head"><h2>PTM Records</h2><button class="btn" onclick="EC.addPTM()">＋ Add PTM</button></div><div class="ec-list">${S.ptm.map(x=>{const s=S.students.find(z=>z.id===x.studentId);return `<div class="card"><b>${esc(s?.name||x.studentId)}</b><p>${x.date} • ${esc(x.status)}</p><p>${esc(x.note||'')}</p><button class="btn ghost" onclick="EC.delPTM('${x.id}')">Delete</button></div>`}).join('')||'<div class="ec-empty">No PTM records.</div>'}</div>`)}
function addPTM(){modal('Add PTM',`<div class="ec-form"><label>Student</label><select id="p_student">${S.students.map(s=>`<option value="${s.id}">${esc(s.name)} (${s.class}-${s.section})</option>`).join('')}</select><label>Date</label><input id="p_date" type="date" value="${today()}"><label>Status</label><select id="p_status"><option>Attended</option><option>Not attended</option></select><label>Note</label><textarea id="p_note"></textarea><button class="btn" onclick="EC.savePTM()">Save</button></div>`)}function savePTM(){S.ptm.push({id:uid('ptm'),studentId:document.getElementById('p_student').value,date:document.getElementById('p_date').value,status:document.getElementById('p_status').value,note:document.getElementById('p_note').value});save();document.querySelector('.ec-modal')?.remove();ptm()}function delPTM(id){S.ptm=S.ptm.filter(x=>x.id!==id);save();ptm()}
function exam(){setTitle('Exam Schedule','Upcoming exams');put(`<div class="head"><h2>Exam Schedule</h2>${role()!=='Student'?'<button class="btn" onclick="EC.addExam()">＋ Add Exam</button>':''}</div><div class="ec-list">${S.exams.filter(x=>role()!=='Student'||(x.class===me().class&&x.section===me().section)).sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<div class="card"><div class="badge">${esc(x.subject)}</div><h3>${esc(x.title)}</h3><p>${esc(x.date)} • ${esc(x.time||'')}</p><div class="ec-muted">Class ${esc(x.class)}-${esc(x.section)}</div>${role()!=='Student'?`<button class="btn ghost" onclick="EC.delExam('${x.id}')">Delete</button>`:''}</div>`).join('')||'<div class="ec-empty">No exams scheduled.</div>'}</div>`)}
function addExam(){modal('Add Exam',`<div class="ec-form"><label>Title</label><input id="e_title"><label>Subject</label><input id="e_subject"><label>Class</label><input id="e_class" value="11"><label>Section</label><input id="e_section" value="A"><label>Date</label><input id="e_date" type="date" value="${today()}"><label>Time</label><input id="e_time" value="10:00"><button class="btn" onclick="EC.saveExam()">Save</button></div>`)}function saveExam(){const x={id:uid('ex'),title:document.getElementById('e_title').value,subject:document.getElementById('e_subject').value,class:document.getElementById('e_class').value,section:document.getElementById('e_section').value,date:document.getElementById('e_date').value,time:document.getElementById('e_time').value};S.exams.push(x);notify('Exam scheduled',x.title,'exam',`${x.class}-${x.section}`);save();document.querySelector('.ec-modal')?.remove();exam()}function delExam(id){S.exams=S.exams.filter(x=>x.id!==id);save();exam()}
function fees(){setTitle('Fees','Fee status');const m=me();if(role()==='Student'){const f=S.fees?.find(x=>x.studentId===m.id)||{total:0,paid:0};put(`<div class="grid2"><div class="card"><div class="ec-kpi">₹${f.total}</div><div class="muted">Total fee</div></div><div class="card"><div class="ec-kpi">₹${f.paid}</div><div class="muted">Paid</div></div></div>`);return}S.fees=S.fees||[];put(`<div class="head"><h2>Fee Records</h2><button class="btn" onclick="EC.addFee()">＋ Add Fee</button></div><div class="ec-list">${S.fees.map(f=>{const s=S.students.find(x=>x.id===f.studentId);return `<div class="card"><b>${esc(s?.name||f.studentId)}</b><p>Total ₹${f.total} • Paid ₹${f.paid}</p></div>`}).join('')||'<div class="ec-empty">No fee records.</div>'}</div>`)}
function addFee(){S.fees=S.fees||[];modal('Add Fee',`<div class="ec-form"><label>Student</label><select id="fee_s">${S.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><label>Total</label><input id="fee_t" type="number"><label>Paid</label><input id="fee_p" type="number"><button class="btn" onclick="EC.saveFee()">Save</button></div>`)}function saveFee(){S.fees.push({id:uid('fee'),studentId:document.getElementById('fee_s').value,total:Number(document.getElementById('fee_t').value),paid:Number(document.getElementById('fee_p').value)});save();document.querySelector('.ec-modal')?.remove();fees()}
function leave(){setTitle('Leave','Apply and track leave');const r=role(),m=me();if(r==='Student'){const rows=S.leaves.filter(x=>x.studentId===m.id);put(`<div class="head"><h2>My Leave</h2><button class="btn" onclick="EC.addLeave()">＋ Apply</button></div><div class="ec-list">${rows.map(x=>`<div class="card"><div class="badge">${esc(x.status)}</div><h3>${esc(x.from)} → ${esc(x.to)}</h3><p>${esc(x.reason)}</p></div>`).join('')||'<div class="ec-empty">No leave applications.</div>'}</div>`);return}put(`<div class="head"><h2>Leave Applications</h2></div><div class="ec-list">${S.leaves.map(x=>{const s=S.students.find(z=>z.id===x.studentId);return `<div class="card"><b>${esc(s?.name||'Student')}</b><p>${x.from} → ${x.to}</p><p>${esc(x.reason)}</p><div class="ec-actions"><button class="btn alt" onclick="EC.leaveStatus('${x.id}','Approved')">Approve</button><button class="btn ghost" onclick="EC.leaveStatus('${x.id}','Rejected')">Reject</button></div></div>`}).join('')||'<div class="ec-empty">No applications.</div>'}</div>`)}
function addLeave(){modal('Apply Leave',`<div class="ec-form"><label>From</label><input id="lv_from" type="date" value="${today()}"><label>To</label><input id="lv_to" type="date" value="${today()}"><label>Reason</label><textarea id="lv_reason"></textarea><button class="btn" onclick="EC.saveLeave()">Submit</button></div>`)}function saveLeave(){const m=me();S.leaves.push({id:uid('lv'),studentId:m.id,from:document.getElementById('lv_from').value,to:document.getElementById('lv_to').value,reason:document.getElementById('lv_reason').value,status:'Pending'});notify('Leave application','A new leave application was submitted.','leave');save();document.querySelector('.ec-modal')?.remove();leave()}function leaveStatus(id,status){const x=S.leaves.find(z=>z.id===id);x.status=status;notify('Leave '+status,x.reason,'leave');save();leave()}
function events(){setTitle('School Events','Activities and announcements');put(`<div class="head"><h2>Events</h2>${role()!=='Student'?'<button class="btn" onclick="EC.addEvent()">＋ Add Event</button>':''}</div><div class="ec-list">${S.events.map(x=>`<div class="card"><div class="badge">${x.date}</div><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p>${role()!=='Student'?`<button class="btn ghost" onclick="EC.delEvent('${x.id}')">Delete</button>`:''}</div>`).join('')||'<div class="ec-empty">No events yet.</div>'}</div>`)}
function addEvent(){modal('Add Event',`<div class="ec-form"><label>Title</label><input id="ev_title"><label>Date</label><input id="ev_date" type="date" value="${today()}"><label>Description</label><textarea id="ev_desc"></textarea><button class="btn" onclick="EC.saveEvent()">Save</button></div>`)}function saveEvent(){S.events.push({id:uid('ev'),title:document.getElementById('ev_title').value,date:document.getElementById('ev_date').value,description:document.getElementById('ev_desc').value});save();document.querySelector('.ec-modal')?.remove();events()}function delEvent(id){S.events=S.events.filter(x=>x.id!==id);save();events()}
function feedback(){setTitle('Feedback','Share your feedback with school');if(role()!=='Student'){put(`<div class="ec-list">${S.feedback.map(f=>`<div class="card"><b>${esc(f.name||'User')}</b><p>${esc(f.text)}</p><div class="ec-muted">${f.date}</div></div>`).join('')||'<div class="ec-empty">No feedback yet.</div>'}</div>`);return}put(`<div class="card"><textarea id="fb" class="textarea" placeholder="Write your feedback..."></textarea><button class="btn" style="margin-top:10px" onclick="EC.saveFeedback()">Send Feedback</button></div>`)}function saveFeedback(){S.feedback.push({id:uid('fb'),studentId:me().id,name:me().name,text:document.getElementById('fb').value,date:today()});save();feedback();toast('Feedback sent')}
function schoolManage(){setTitle('School Management','Demo school setup');if(role()==='Student'){return go('home')}put(`<div class="grid2"><div class="card"><h3>School</h3><p><b>${esc(S.school.name)}</b></p><p>Code: ${esc(S.school.code)}</p></div><div class="card"><h3>Counts</h3><p>Students: ${S.students.length}</p><p>Teachers: ${S.teachers.length}</p></div><div class="card"><h3>Classes</h3><p>${S.school.classes.map(esc).join(', ')}</p></div><div class="card"><h3>Sections</h3><p>${S.school.sections.map(esc).join(', ')}</p></div><div class="card"><h3>Subjects</h3><p>${S.school.subjects.map(esc).join(', ')}</p></div><div class="card"><h3>Multi-school ready</h3><p class="muted">The prototype stores a school code and keeps school data grouped in one local dataset. A real multi-school deployment needs a secure backend/database.</p></div></div>`)}
function applyTheme(){const pref=S.settings.theme;const dark=pref==='dark'||(pref==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);document.body.dataset.theme=pref}
function theme(v){S.settings.theme=v;save();applyTheme();settings()}function notifToggle(){S.settings.notifications=!S.settings.notifications;save();settings()}function language(v){S.settings.language=v;save();toast('Language preference saved')}
window.EC={go,side,logout,switchAcc,theme,notifToggle,language,addHW,editHW,saveHW,delHW,submitHW,loadAtt,markAllAtt,saveAtt,addResult,editResult,saveResult,toggleResult,delResult,addNotice,editNotice,saveNotice,readNotice,delNotice,study,askAI,voiceIn,speakLast,fileAI,clearAI,addPTM,savePTM,delPTM,addExam,saveExam,delExam,addFee,saveFee,addLeave,saveLeave,leaveStatus,addEvent,saveEvent,delEvent,saveFeedback};
window.addEventListener('storage',()=>{S=load();if(S.current)render()});
window.matchMedia?.('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(S.settings.theme==='system')applyTheme()});
if(!S.current)login();else render();
})();
